apiVersion: v1
kind: ConfigMap
metadata:
  name: example-resume-api-config
data:
  MONGO_URL: "mongodb://mongodb-service:27017"
  MONGO_DB_NAME: "resumeDB"
  USER_EMAIL: "your-email@example.com"
  USER_NAME: "Your Name"
  USER_LOCATION: "Your City, Province"
  USER_PHONE: "Your Phone Number"
